SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE users;
TRUNCATE TABLE roles;
TRUNCATE TABLE products;
TRUNCATE TABLE categories;
TRUNCATE TABLE categoryItems;
TRUNCATE TABLE orders;
TRUNCATE TABLE orderItems;